### ISSUE TITLE
Profile photo for the bot.

### ISSUE THREAD

**Issue by ArionMiles** [ArionMiles/MIS-Bot#13]
Telegram requires a 600*600px image for the userpic. Suggestions are welcome.

**Comment by agauniyal** [comment]
![memelovetriangle_297886754](https://user-images.githubusercontent.com/7630575/35411581-52ea0632-023f-11e8-8639-dde29ae33254.jpg)

**Comment by ArionMiles** [comment]
Not what I was looking for @agauniyal but thanks!

**Comment by ArionMiles** [comment]
I'm going with @bleeptrack's version. Checkout pull #23
